import type { QuestTask } from "./types";

// The task pool, signed off by Edgar on October 1, 2026. Source of truth for review: docs/tasks/task-pool.md (011
// onwards) and docs/research/task-design-guide.md §5 (001 to 010). Never reuse or renumber an id: task history keys
// on it.
export const questTaskPool: QuestTask[] = [
  // Introductory
  {
    id: "intro-001",
    category: "intro",
    title: "Name this walk",
    prompt: "Every good adventure needs a title. Give today's walk the name of a film.",
    steps: ["Each suggest one title", "Pick one together, or mix them"],
    photoHint: "You two, looking like the film poster",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-002",
    category: "intro",
    title: "Three words",
    prompt: "How do you feel right now? Say it in three words, then guess your partner's.",
    steps: ["Each think of three words", "Guess the other's first word", "Reveal and compare"],
    photoHint: "Your faces, showing word number one",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-003",
    category: "intro",
    title: "Small happy thing",
    prompt: "What small thing made you happy this week? Tell it like a tiny story.",
    steps: ["One tells", "The other asks one question about it", "Swap"],
    photoHint: "Two thumbs up, one each",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-004",
    category: "intro",
    title: "First thing I saw",
    prompt: "What is the first thing you noticed about your partner? Be honest and be kind.",
    steps: ["One tells", "The other says what they remember about that day", "Swap"],
    photoHint: "The same pose as your first photo together, if you remember it",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-005",
    category: "intro",
    title: "Walk soundtrack",
    prompt: "If this walk had a song, what would it be? Hum a little of it.",
    steps: ["Each pick a song", "Hum ten seconds", "The other guesses it"],
    photoHint: 'A "music video" still of you two',
    tags: ["talk", "voice", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-006",
    category: "intro",
    title: "Weirdly good at",
    prompt: "Everyone is weirdly good at something. What are you weirdly good at?",
    steps: ["One tells", "The other asks for a small demo, if possible", "Swap"],
    photoHint: "The demo, or your proudest face",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-007",
    category: "intro",
    title: "Walk promise",
    prompt: "Make one small, silly promise for this walk.",
    steps: ['Each make a promise ("I will point at every dog")', "Shake hands on it"],
    photoHint: "The handshake",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-008",
    category: "intro",
    title: "Kid you",
    prompt: "Eight-year-old you can see you two right now. What would little you say?",
    steps: ["One answers in a kid voice", "The other answers as their kid self", "Laugh"],
    photoHint: "Your best eight-year-old faces",
    tags: ["talk", "voice", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-009",
    category: "intro",
    title: "Looking forward",
    prompt: "What are you looking forward to this month?",
    steps: ["One tells", 'The other asks, "What part are you most excited about?"', "Swap"],
    photoHint: "You two looking forward, into the distance",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-010",
    category: "intro",
    title: "Sky report",
    prompt: "Look up together. Describe the sky like a weather reporter who loves their job.",
    steps: ["One reports for 20 seconds", 'The other adds a "breaking news" update', "Swap roles"],
    photoHint: "Selfie with the sky behind you",
    tags: ["voice", "outdoors-only", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-011",
    category: "intro",
    title: "Pocket pact",
    prompt: "Keep one phone for the map. The other goes on silent, in a pocket, until the next stop.",
    steps: [
      "Decide whose phone shows the map",
      "The other phone goes away",
      "Each name one thing you'll look at instead",
    ],
    photoHint: "Two hands, one phone",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-012",
    category: "intro",
    title: "No-logistics rule",
    prompt: "Until stop three, no talk of shopping, bills, or plans. Whoever slips pays the other a compliment.",
    steps: ["Shake on the rule", "Each name one topic you'll talk about instead", "Pay compliments kindly if you slip"],
    photoHint: "You two, zipping your lips",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-013",
    category: "intro",
    title: "You at fifteen",
    prompt: "Tell one thing about yourself at fifteen that your partner has never heard.",
    steps: ["One tells", "The other asks one question about it", "Swap"],
    photoHint: "Your best fifteen-year-old faces",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-014",
    category: "intro",
    title: "Day in one word",
    prompt: "Each give one word for your day so far. Your partner guesses why you chose it.",
    steps: ["Both say your word", "Each guesses the other's reason", "Tell the real reason"],
    photoHint: "Your faces, each showing your word",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-015",
    category: "intro",
    title: "Our first outing",
    prompt: "What is the first walk or outing you two remember? Each share one detail the other may have forgotten.",
    steps: ["One shares a detail", "The other adds one of their own", "Swap until you run out"],
    photoHint: "The same smiles as that day",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-016",
    category: "intro",
    title: "Energy forecast",
    prompt: "Give your energy today as a weather forecast: drizzle, clouds, or full sunshine.",
    steps: ["Each give your forecast", "Say what would make it sunnier", "Agree on a pace for the walk"],
    photoHint: "Your weather, shown with your arms",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-017",
    category: "intro",
    title: "One hour anywhere",
    prompt: "You can be anywhere in the world for one hour, right now. Where do you go?",
    steps: ["One answers", 'The other asks, "What do you do first?"', "Swap"],
    photoHint: "You two, looking towards your places",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-018",
    category: "intro",
    title: "Useless superpower",
    prompt: "You each get one small, useless superpower for today. What is yours?",
    steps: [
      "Each choose a power",
      "The other asks how it helps on this walk",
      "Decide which power makes a better team",
    ],
    photoHint: "Your superhero poses",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-019",
    category: "intro",
    title: "Three sounds",
    prompt: "Stand still together and listen for 20 seconds. Then each name three sounds you heard.",
    steps: [
      "Find a safe spot and stand still",
      "Listen quietly for 20 seconds",
      "Compare: did you hear the same things?",
    ],
    photoHint: "You two, listening",
    tags: ["quiet", "outdoors-only", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-020",
    category: "intro",
    title: "Childhood snack",
    prompt: "What was your favourite snack as a kid? Describe it so well your partner can almost taste it.",
    steps: ["One describes it", "The other guesses what it tasted like", "Swap"],
    photoHint: 'Your "tasting it" faces',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-021",
    category: "intro",
    title: "Best compliment",
    prompt: "What is the best compliment anyone ever gave you? Why do you still remember it?",
    steps: ["One tells", "The other says why it fits", "Swap"],
    photoHint: "You two, looking pleased with yourselves",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-022",
    category: "intro",
    title: "Tiny win",
    prompt: "What small thing did you do well this week? Brag a little. It's allowed.",
    steps: ["One brags for 30 seconds", "The other cheers like a sports fan; quietly is fine", "Swap"],
    photoHint: "The winner on the other's shoulders, or a fist",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-023",
    category: "intro",
    title: "Explorer names",
    prompt: "Every explorer needs a name. Give your partner an explorer name for today.",
    steps: ["Each invent a name for the other", "Explain it in one sentence", "Use the names until the next stop"],
    photoHint: "Two explorers, looking into the distance",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-024",
    category: "intro",
    title: "Our song",
    prompt: "Which song reminds you of when you met? If none does, invent a title for one.",
    steps: ["Each name a song or a title", "Say what it reminds you of", "Agree on one for today"],
    photoHint: "The album cover for your song",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-025",
    category: "intro",
    title: "One-day job",
    prompt: "You can try any job for one day. Which one do you pick?",
    steps: ["One names the job", "The other guesses the part you'd love most", "Swap"],
    photoHint: 'You two "at work" in your new jobs',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-026",
    category: "intro",
    title: "Never noticed",
    prompt: "Each find one thing here you have never noticed before. Show it to your partner.",
    steps: ["Look around for a minute", "Show your thing", "The other says one nice thing about it"],
    photoHint: "Your two discoveries",
    tags: ["quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-027",
    category: "intro",
    title: "Lazy Sunday",
    prompt: "Describe a perfect lazy Sunday, from waking up to bedtime.",
    steps: ["One describes theirs", "The other describes theirs", "Find the parts that match"],
    photoHint: "You two, as relaxed as you can look",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-028",
    category: "intro",
    title: "Secret habit",
    prompt: "What tiny habit of yours might surprise your partner? Something you do when nobody's watching.",
    steps: ["One tells", "The other asks one question about it", "Swap"],
    photoHint: 'A "caught in the act" photo',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-029",
    category: "intro",
    title: "Long-lost hello",
    prompt: "Greet your partner as if you haven't seen each other for a whole year.",
    steps: ["One does the big greeting", "The other greets back, even bigger", "Then a normal hello"],
    photoHint: "The reunion hug",
    tags: ["voice", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-030",
    category: "intro",
    title: "Three new questions",
    prompt: "Ask your partner three quick questions you have never asked. Keep them light.",
    steps: ["One asks three questions", "The other answers each in a sentence", "Swap"],
    photoHint: "You two, mid-laugh",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  // Silly game
  {
    id: "silly-001",
    category: "silly",
    title: "Nature film",
    prompt: "One of you is a rare animal. The other is a nature film narrator, whispering.",
    steps: [
      'Narrator whispers for 45 seconds about the "animal" and its habits',
      "Animal acts it out, quietly",
      "Swap",
    ],
    photoHint: "The rare animal in its natural home",
    tags: ["voice", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-002",
    category: "silly",
    title: "Human statue",
    prompt: 'Together, build one statue called "The Victory of Us".',
    steps: [
      "Agree on a pose in ten seconds",
      "Hold it, both still, for ten seconds",
      "Make a second version, bigger or smaller",
    ],
    photoHint: "The statue, of course",
    tags: ["move", "quiet"],
    minutes: 3,
  },
  {
    id: "silly-003",
    category: "silly",
    title: "Secret agents",
    prompt: "You are secret agents. Choose your code names and invent a secret handshake.",
    steps: ["Each pick the other's code name", "Build a handshake with at least four moves", "Do it twice, perfectly"],
    photoHint: "The handshake, mid-move",
    tags: ["move", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-004",
    category: "silly",
    title: "Fake tour guide",
    prompt: "Pick the nearest ordinary thing: a bench, a tree, a lamp. Invent its amazing history.",
    steps: [
      "One is the proud guide for 30 seconds",
      "The other is a tourist and asks one question",
      "Swap, new object",
    ],
    photoHint: 'The guide presenting the "famous" object',
    tags: ["voice", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-005",
    category: "silly",
    title: "One word each",
    prompt: 'Tell a story together, one word at a time. It starts with "Once, on a walk…"',
    steps: ["Take turns, one word each", "Keep going for one minute", "Give the story a title"],
    photoHint: "Your faces at the story's ending",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-006",
    category: "silly",
    title: "Slow-motion race",
    prompt: "Find a safe, open spot. Race over ten steps, in slow motion. The slowest wins.",
    steps: ["Stand side by side", "Move as slowly as you can, with dramatic faces", "Replay the finish, even slower"],
    photoHint: "The dramatic finish",
    tags: ["move", "energetic", "outdoors-only"],
    minutes: 3,
  },
  {
    id: "silly-007",
    category: "silly",
    title: "Band cover",
    prompt: "You are a band now. Name it after two things you can see from here.",
    steps: ["Each point at one thing", "Combine them into a band name", "Pose for the album cover"],
    photoHint: "The album cover",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-008",
    category: "silly",
    title: "Opera time",
    prompt: "Say normal things, but sing them like an opera. Softly is fine.",
    steps: [
      "One sings a sentence about what they see",
      "The other sings back an answer",
      "Keep going for four lines each",
    ],
    photoHint: "Your most dramatic opera faces",
    tags: ["voice", "energetic", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-009",
    category: "silly",
    title: "Mirror, mirror",
    prompt: "Stand face to face. One leads slow moves, the other is the mirror.",
    steps: [
      "Leader moves slowly for 30 seconds",
      "Mirror copies exactly",
      "Swap, then try to move together with no leader",
    ],
    photoHint: "Both of you in the same pose",
    tags: ["move", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-010",
    category: "silly",
    title: "Sell this spot",
    prompt: "Make a 30-second advert for this exact spot. It is the best place on Earth.",
    steps: ["Plan it together in one minute", "Both speak in the advert", "Film it if you like, or just perform it"],
    photoHint: "The poster for your advert",
    tags: ["voice", "energetic", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-011",
    category: "silly",
    title: "Tiny wonders",
    prompt: "Each find three small things here. Your partner reacts to each like it is the best thing ever.",
    steps: [
      "Take turns showing one small thing",
      "The other reacts with huge excitement; quietly is fine",
      "Three each",
    ],
    photoHint: "The best tiny thing you found",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-012",
    category: "silly",
    title: "Object compliment",
    prompt:
      'Pick an object here and use it to compliment your partner: "You are like this lamp. You light up my evenings."',
    steps: ["Each pick an object", "Make your compliment", "The other gives it a score out of ten bananas; swap"],
    photoHint: "You, with your object",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-013",
    category: "silly",
    title: "Secret name",
    prompt: "Find something here with a funny shape. Give it a secret name only you two know.",
    steps: ["Each suggest a name", "Pick the best one", "Use it at least once more today"],
    photoHint: "You two with the newly named thing",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-014",
    category: "silly",
    title: "Would you rather",
    prompt: 'Play "Would you rather" using only things you can see from here.',
    steps: [
      'One asks: "Live in that window or sleep under that tree?"',
      "Both answer and say why",
      "Three questions each",
    ],
    photoHint: "You two, pointing at your choices",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-015",
    category: "silly",
    title: "Same answer",
    prompt: "On three, both point at the best thing here: best window, best tree, best cloud. Can you match?",
    steps: ["Pick a category", "Count to three and point", "Play five rounds and count your matches as a team"],
    photoHint: "Both of you pointing at the same thing",
    tags: ["quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-016",
    category: "silly",
    title: "Robot partner",
    prompt: "One of you is a robot that only does exactly what it's told. Get the robot to sit down.",
    steps: ["Find a safe, open spot", 'Give tiny, exact orders ("lift your left foot a little")', "Swap"],
    photoHint: "The robot, mid-move",
    tags: ["move", "quiet"],
    minutes: 4,
  },
  {
    id: "silly-017",
    category: "silly",
    title: "Accent swap",
    prompt: "Describe what you see in a made-up accent. Your partner answers in a different one.",
    steps: ["One describes for 30 seconds", "The other answers in their accent", "Swap accents"],
    photoHint: 'Your most "foreign" faces',
    tags: ["voice", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-018",
    category: "silly",
    title: "Slow-motion high five",
    prompt: "Do the most dramatic slow-motion high five of all time.",
    steps: [
      "Stand a few steps apart in a safe, open spot",
      "Move together in slow motion, with sound effects",
      "Meet in the middle",
    ],
    photoHint: "The moment your hands meet",
    tags: ["move", "energetic"],
    minutes: 3,
  },
  {
    id: "silly-019",
    category: "silly",
    title: "Emoji face",
    prompt: "Make an emoji with your face. Your partner guesses which one.",
    steps: ["One makes an emoji", "The other guesses", "Three each, then make one together"],
    photoHint: "Your best emoji, together",
    tags: ["quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-020",
    category: "silly",
    title: "Two truths, one lie",
    prompt: "Tell your partner two true things and one made-up thing about your day. They guess the lie.",
    steps: ["One tells three things", "The other guesses the lie", "Swap"],
    photoHint: "The guesser's thinking face",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-021",
    category: "silly",
    title: "Movie trailer",
    prompt: 'Do the trailer for the film of your walk so far. Start with "In a world…"',
    steps: ["One is the trailer voice", "The other adds the dramatic sounds", "Swap for the sequel"],
    photoHint: "The film poster",
    tags: ["voice", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-022",
    category: "silly",
    title: "Body letters",
    prompt: "Make letters with your bodies, together. Spell a short word.",
    steps: ["Choose a word with three letters", "Make each letter as a team", "Pick your best letter"],
    photoHint: "Your best letter",
    tags: ["move", "quiet"],
    minutes: 4,
  },
  {
    id: "silly-023",
    category: "silly",
    title: "Shadow animals",
    prompt: "Make an animal with your hands, as a shadow or in the air. Your partner guesses it.",
    steps: ["One makes an animal", "The other guesses", "Three each, then make one animal with four hands"],
    photoHint: "The four-handed animal",
    tags: ["quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-024",
    category: "silly",
    title: "Secret word",
    prompt: "Each choose a secret word. Get your partner to say it, without saying it yourself.",
    steps: [
      "Each pick a word and keep it secret",
      "Talk normally and steer them towards it",
      "Reveal it when they say it",
    ],
    photoHint: "The winner's surprised face",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-025",
    category: "silly",
    title: "Conductor",
    prompt: "One of you conducts an invisible orchestra. The other makes the music with sounds.",
    steps: ["The conductor shows fast, slow, loud, and soft", "The musician hums or whistles along", "Swap"],
    photoHint: "The conductor, mid-swing",
    tags: ["voice", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-026",
    category: "silly",
    title: "Yes, and",
    prompt: 'Plan an impossible holiday together. Every sentence must start with "Yes, and…"',
    steps: [
      'One starts: "Let\'s go to the Moon"',
      'Take turns adding a detail with "Yes, and"',
      "Keep going for one minute",
    ],
    photoHint: "You two, ready for take-off",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-027",
    category: "silly",
    title: "Animal walk",
    prompt: "Walk ten steps like an animal. Your partner guesses which one.",
    steps: ["Find a safe, open spot", "One walks like an animal", "The other guesses; swap"],
    photoHint: "Both of you as the same animal",
    tags: ["move", "energetic", "outdoors-only"],
    minutes: 3,
  },
  {
    id: "silly-028",
    category: "silly",
    title: "Puppet show",
    prompt: "One of you is a puppet. The other speaks for them while the puppet moves only its mouth.",
    steps: [
      "The puppeteer stands just behind",
      "The puppeteer talks about this place; the puppet mouths the words",
      "Swap",
    ],
    photoHint: "The puppet and its master",
    tags: ["voice", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-029",
    category: "silly",
    title: "Guess the statue",
    prompt: "Make a statue with your body. Your partner guesses its title.",
    steps: ["One makes a statue", "The other guesses the title", "Three each, then one statue together"],
    photoHint: "The statue you made together",
    tags: ["move", "quiet"],
    minutes: 3,
  },
  {
    id: "silly-030",
    category: "silly",
    title: "Mind meld",
    prompt: "On three, each say any word. Then both try to say a word that links them, until you say the same word.",
    steps: [
      "Count to three and each say a word",
      "Think of a word between them",
      "Say it on three; keep going until you match",
    ],
    photoHint: "Your faces when you finally match",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-031",
    category: "silly",
    title: "Spy report",
    prompt: "You are spies. Report everything suspicious about this place to headquarters. Things only, never people.",
    steps: [
      "One whispers a report for 30 seconds: the nervous tree, the bench that knows too much",
      "The other is headquarters and gives a silly new mission",
      "Swap",
    ],
    photoHint: "Two spies, trying not to be seen",
    tags: ["voice", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-032",
    category: "silly",
    title: "Tongue twisters",
    prompt: "Say a tongue twister three times fast, in any language. Then invent one about your partner.",
    steps: ["Each say one you know", "Invent a new one about the other", "Try the new ones three times fast"],
    photoHint: "Your faces after the twister",
    tags: ["voice", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-033",
    category: "silly",
    title: "Invisible gift",
    prompt: "Give your partner an invisible gift. They must guess what it is from how you hand it over.",
    steps: ["Show its size and weight as you hand it over", "The other unwraps it and reacts", "Guess, then swap"],
    photoHint: "Unwrapping the invisible gift",
    tags: ["quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-034",
    category: "silly",
    title: "Fortune teller",
    prompt: "Read your partner's palm. Predict three silly, kind things for next week.",
    steps: ["Hold their hand and study it seriously", "Make three predictions", "Swap"],
    photoHint: "The fortune teller at work",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-035",
    category: "silly",
    title: "Round things",
    prompt: "In one minute, together, find five round things here. Point, don't pick.",
    steps: ["Start the minute", "Point at each thing you find", "Then try five things of one colour"],
    photoHint: "The best round thing you found",
    tags: ["move", "quiet"],
    minutes: 3,
  },
  {
    id: "silly-036",
    category: "silly",
    title: "Big match commentary",
    prompt: "One does a simple action, like tying a shoe. The other commentates like it is the final of the World Cup.",
    steps: ["One picks an everyday action", "The other commentates, full of drama", "Swap"],
    photoHint: "The champion, celebrating",
    tags: ["voice", "energetic", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-037",
    category: "silly",
    title: "Opposite minute",
    prompt: 'For one minute, say the opposite of what you mean: "This walk is terrible." Your partner translates.',
    steps: ["One speaks in opposites", "The other translates out loud", "Swap"],
    photoHint: 'Your most "opposite" faces',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-038",
    category: "silly",
    title: "Thumb war",
    prompt: "Thumb war, best of three. Then a rematch with the other hand.",
    steps: ["Hook your fingers together", 'Count "one, two, three, four, I declare a thumb war"', "Play, then rematch"],
    photoHint: "Two thumbs, mid-battle",
    tags: ["quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-039",
    category: "silly",
    title: "Rhyme time",
    prompt: "Make a two-line poem about this place. You say line one, your partner rhymes line two.",
    steps: ["One says a line", "The other finishes with a rhyme", "Swap who starts; make three poems"],
    photoHint: "You two, looking like serious poets",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-040",
    category: "silly",
    title: "Alien visitors",
    prompt: "You are aliens seeing Earth for the first time. Explain to each other what that thing is for.",
    steps: [
      "Pick an ordinary thing: a bench, a sign, a bin",
      "One explains, very sure and very wrong",
      "The other adds an alien theory; swap",
    ],
    photoHint: "Two aliens studying the object",
    tags: ["voice", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-041",
    category: "silly",
    title: "Copy my clap",
    prompt: "One claps a rhythm. The other copies it. Make it longer each time.",
    steps: ["One claps a short rhythm", "The other copies it", "Add one clap each round; swap leaders"],
    photoHint: "Your hands, mid-clap",
    tags: ["quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-042",
    category: "silly",
    title: "Freeze dance",
    prompt: "One hums a tune; the other dances. When the humming stops, freeze.",
    steps: [
      "Find a safe, open spot",
      "Hum, dance, and freeze three times",
      "Swap; dancing with only your hands is fine",
    ],
    photoHint: "The best freeze",
    tags: ["move", "voice", "energetic"],
    minutes: 3,
  },
  {
    id: "silly-043",
    category: "silly",
    title: "Twenty questions",
    prompt: "Think of an animal. Your partner finds it with yes-or-no questions, twenty at most.",
    steps: ["One thinks of an animal", "The other asks yes-or-no questions", "Swap"],
    photoHint: "You two as that animal",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-044",
    category: "silly",
    title: "Silent film",
    prompt: "Tell your partner about your morning without words, like a silent film.",
    steps: ["One acts out their morning", "The other narrates what they think happened", "Swap"],
    photoHint: "The silent film's most dramatic scene",
    tags: ["quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-045",
    category: "silly",
    title: "Lip reading",
    prompt: "Say a sentence with no sound. Your partner reads your lips.",
    steps: ["One mouths a short sentence", "The other guesses it", "Three each"],
    photoHint: "Your most exaggerated lips",
    tags: ["quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-046",
    category: "silly",
    title: "Catwalk",
    prompt: "Walk ten steps like a top model. Your partner is the fashion commentator.",
    steps: ["Find a safe, open spot", "One walks and poses at the end", 'The other describes the "look"; swap'],
    photoHint: "The pose at the end of the catwalk",
    tags: ["move", "voice", "energetic"],
    minutes: 3,
  },
  {
    id: "silly-047",
    category: "silly",
    title: "Our dance move",
    prompt: "Invent a dance move for two people and give it a name.",
    steps: ["Each suggest one movement", "Join them into one move", "Do it twice and name it"],
    photoHint: "Your new move, mid-step",
    tags: ["move", "energetic"],
    minutes: 4,
  },
  {
    id: "silly-048",
    category: "silly",
    title: "Us at ninety",
    prompt: "Act as yourselves at ninety, on a walk just like this one.",
    steps: [
      "Talk like your old selves for one minute",
      'Each tell one "story from the old days" about today',
      "End with a laugh",
    ],
    photoHint: "Two ninety-year-olds on an adventure",
    tags: ["voice", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-049",
    category: "silly",
    title: "Cloud stories",
    prompt: "Find a cloud with a shape. Tell its story together, one sentence each.",
    steps: ["Find a cloud shape and agree what it is", "Take turns adding a sentence", "Stop when the cloud changes"],
    photoHint: "You two and your cloud",
    tags: ["quiet", "outdoors-only", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-050",
    category: "silly",
    title: "Swap places",
    prompt: "Act as each other for one minute. Be kind: copy what you love.",
    steps: ["One plays the other: how they talk, how they stand", "The other says what was spot on", "Swap"],
    photoHint: "Each of you, doing the other's pose",
    tags: ["voice", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-051",
    category: "silly",
    title: "Category chain",
    prompt: "Take turns naming things in a category, like fruits or cities. Whoever pauses picks the next category.",
    steps: ["Pick a category", "Take turns naming one thing each, fast", "On a pause, the pauser picks a new category"],
    photoHint: "You two, mid-thought",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-052",
    category: "silly",
    title: "Hot and cold",
    prompt: 'One thinks of an object here. The other finds it with "hot" and "cold" hints.',
    steps: ["One picks an object and keeps it secret", 'The other moves around; you say "warmer" or "colder"', "Swap"],
    photoHint: "The finder pointing at the object",
    tags: ["move", "quiet"],
    minutes: 3,
  },
  {
    id: "silly-053",
    category: "silly",
    title: "Perfect sync",
    prompt: "Without talking, try to sit down and stand up at exactly the same time.",
    steps: ["Stand side by side near a bench, or crouch instead", "Look at each other, no words", "Try five times"],
    photoHint: "The moment you were perfectly in sync",
    tags: ["move", "quiet"],
    minutes: 3,
  },
  {
    id: "silly-054",
    category: "silly",
    title: "Evening news",
    prompt: "Present the news about your walk. One is the studio anchor, one is the reporter on the spot.",
    steps: ["The anchor introduces the story", 'The reporter gives the "live" report', "Swap roles"],
    photoHint: "The reporter, live on the scene",
    tags: ["voice", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-055",
    category: "silly",
    title: "Three-thing story",
    prompt: "Each point at one thing here. Together, tell a 30-second story that uses everything you pointed at.",
    steps: ["Each point at one thing", "Take turns telling the story", "Give it a title"],
    photoHint: "The three things in one photo",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-056",
    category: "silly",
    title: "How we met, the play",
    prompt: "Act out how you two met, in 30 seconds. You play every role.",
    steps: ["Agree on the scene", "Act it out, playing everyone", "Do a second take, twice as dramatic"],
    photoHint: "The most dramatic moment",
    tags: ["voice", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-057",
    category: "silly",
    title: "Magazine cover",
    prompt: "On three, both strike a pose for a magazine cover. Then name the magazine.",
    steps: ["Count to three and pose", "Name the magazine and the headline", "Try a second cover"],
    photoHint: "The magazine cover",
    tags: ["quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-058",
    category: "silly",
    title: "Straight face",
    prompt: "Try to make your partner laugh without touching them. They try to stay serious.",
    steps: ["One tries for 30 seconds", "The other keeps a straight face", "Swap"],
    photoHint: "The moment one of you breaks",
    tags: ["quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-059",
    category: "silly",
    title: "Flamingos",
    prompt: "Stand on one foot together, holding hands. Count how long you last as a team.",
    steps: [
      "Find flat ground, away from steps and edges",
      "Hold hands and lift one foot each",
      "Count together; try to beat it",
    ],
    photoHint: "Two flamingos",
    tags: ["move"],
    minutes: 2,
  },
  {
    id: "silly-060",
    category: "silly",
    title: "Fast whispers",
    prompt: "Whisper a sentence into your partner's ear, very fast. They repeat what they heard.",
    steps: ["One whispers fast", "The other repeats it out loud", "Compare; swap"],
    photoHint: "The listener's confused face",
    tags: ["quiet", "seated-ok"],
    minutes: 3,
  },
  // Deep task
  {
    id: "deep-001",
    category: "deep",
    title: "Thank you for",
    prompt: "Think of something small your partner did lately that you liked. Tell them, and say thank you.",
    steps: ["One tells the moment and says thank you", "The other says how it feels to hear it", "Swap"],
    photoHint: "Your hands together",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-002",
    category: "deep",
    title: "Good news, again",
    prompt: "Think of something that went well for you lately, big or small. Share it and celebrate it.",
    steps: [
      "One shares the good news",
      'The other asks, "How did it happen?" and one more question',
      'No "yes, but"',
      "Swap",
    ],
    photoHint: "A celebration pose for each win",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-003",
    category: "deep",
    title: "Close to you",
    prompt: "When did you feel close to your partner lately? Pick one moment.",
    steps: ["One describes the moment: where, when, what happened", "The other says what they remember of it", "Swap"],
    photoHint: "You two, as close as feels right",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-004",
    category: "deep",
    title: "Hidden strength",
    prompt: "Tell your partner one strength they have that they might not see in themselves.",
    steps: ["One names the strength and gives an example", "The other repeats it back in their own words", "Swap"],
    photoHint: "Your partner, looking strong",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-005",
    category: "deep",
    title: "A little more of",
    prompt: "What is one small thing you would love a little more of from your partner?",
    steps: [
      'One says it, starting "I\'d love a little more…"',
      "The other repeats it back and says one way to try",
      "Swap",
    ],
    photoHint: 'Each of you, showing "a little" with your fingers',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-006",
    category: "deep",
    title: "Proud of you",
    prompt: "Remember a time you felt proud of your partner. Tell them about it.",
    steps: ["One tells the story", 'The other asks, "What made you proud?"', "Swap"],
    photoHint: "A proud-parent photo, one of you beaming at the other",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-007",
    category: "deep",
    title: "Feeling cared for",
    prompt: "What small, everyday thing makes you feel cared for?",
    steps: ["One answers with an example", "The other asks one question to understand it better", "Swap"],
    photoHint: "Something near you that looks cosy",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-008",
    category: "deep",
    title: "Learned from you",
    prompt: "What have you learned from your partner since you met?",
    steps: ["One tells, with an example", "The other says thank you and how they feel", "Swap"],
    photoHint: 'A "teacher and student" photo, then swap roles',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-009",
    category: "deep",
    title: "On a hard day",
    prompt: "When you have a hard day, what helps you most? Tell your partner.",
    steps: ["One answers: a word, a hug, space, a snack", "The other repeats it back to check", "Swap"],
    photoHint: "A gentle hug, or a hand on the shoulder",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-010",
    category: "deep",
    title: "Us, later",
    prompt: "Imagine you two, years from now, on a walk like this. What are you talking about?",
    steps: ["One paints the picture", "The other adds one detail", "Swap, then pick your favourite detail"],
    photoHint: "You two walking away from the camera",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-011",
    category: "deep",
    title: "Close when",
    prompt: 'Finish this sentence: "I feel close to you when…" Give one real example.',
    steps: ["One finishes the sentence", 'The other repeats it back: "So when I…"', "Swap"],
    photoHint: "You two, as close as feels right",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-012",
    category: "deep",
    title: "Nobody thanks you",
    prompt: "Name one thing your partner does that maybe nobody thanks them for. Thank them now.",
    steps: ["One names it and says thank you", "The other says how it feels to hear", "Swap"],
    photoHint: "A thank-you handshake",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-013",
    category: "deep",
    title: "This year",
    prompt: "What has changed in your partner this year that you admire? Give an example.",
    steps: ["One tells, with an example", "The other says what it is like to be seen", "Swap"],
    photoHint: "Your partner, looking at the view",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-014",
    category: "deep",
    title: "Bring it back",
    prompt: "What did you two used to do together that you'd love to do again?",
    steps: ["Each name one thing", "The other asks what you loved about it", "Pick one to bring back soon"],
    photoHint: "The two of you, recreating it in a pose",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-015",
    category: "deep",
    title: "A year from now",
    prompt: "What would you love the two of you to have done together a year from now? Small or big.",
    steps: ["One says it", "The other adds one detail that makes it better", "Swap"],
    photoHint: "You two, looking ahead",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-016",
    category: "deep",
    title: "There for me",
    prompt: "Tell your partner about a time they were there for you when it mattered.",
    steps: ["One tells: when, where, what they did", "The other says what they remember", "Swap"],
    photoHint: "A hand on the shoulder",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-017",
    category: "deep",
    title: "Small ways",
    prompt: "How does your partner show love in small ways? Name two they may not know you notice.",
    steps: ["One names two small things", 'The other asks, "How did you notice?"', "Swap"],
    photoHint: "Something small and lovely near you",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-018",
    category: "deep",
    title: "When life is busy",
    prompt: "When life gets busy, what small thing from your partner would mean the most?",
    steps: [
      'One says it, starting "It would mean a lot if…"',
      "The other repeats it back and asks one question",
      "Swap",
    ],
    photoHint: "Your hands, holding on",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-019",
    category: "deep",
    title: "Really listened",
    prompt: "Think of a time you felt really listened to by your partner. What did they do?",
    steps: ["One describes the moment", "The other says what they remember of it", "Swap"],
    photoHint: "One of you listening, the other talking",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-020",
    category: "deep",
    title: "Quiet dream",
    prompt: "What is a small dream you haven't talked about much?",
    steps: ["One shares the dream", "The other asks one question and suggests one way to help", "Swap"],
    photoHint: "You two, looking up",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-021",
    category: "deep",
    title: "Again, please",
    prompt: "Describe one day from your life together that you would happily live again.",
    steps: ["One describes the day", "The other adds what they remember", "Swap"],
    photoHint: "The same pose as on that day, if you can",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-022",
    category: "deep",
    title: "With other people",
    prompt: "What do you admire about how your partner treats other people? Give an example.",
    steps: ["One tells, with an example", "The other says thank you and how it feels", "Swap"],
    photoHint: "Your partner, smiling",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-023",
    category: "deep",
    title: "Our little thing",
    prompt: "What small thing that you do together do you secretly love? A word, a habit, a joke.",
    steps: ["One names it", "The other says why they love it too", "Swap"],
    photoHint: "You two, doing that little thing",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-024",
    category: "deep",
    title: "Better since",
    prompt: "What is better in your life since you met your partner? Give one specific example.",
    steps: ["One tells, with an example", "The other asks one question about it", "Swap"],
    photoHint: "You two, side by side",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-025",
    category: "deep",
    title: "At home with you",
    prompt: "When do you feel most at home with your partner? A place, a moment, a time of day.",
    steps: ["One describes it", "The other says what they picture", "Swap"],
    photoHint: "Something here that feels like home",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-026",
    category: "deep",
    title: "I'm here",
    prompt: 'Agree on a tiny signal that means "I see you, I\'m here": a squeeze, a wink, a word.',
    steps: ["Each suggest a signal", "Choose one together", "Try it now, and use it this week"],
    photoHint: "The signal, caught on camera",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "deep-027",
    category: "deep",
    title: "At your best",
    prompt: "When have you seen your partner at their best, doing something they love?",
    steps: ["One describes the moment", "The other says what that activity means to them", "Swap"],
    photoHint: 'Your partner, in their "best" pose',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-028",
    category: "deep",
    title: "Short thank-you letter",
    prompt: "Say a three-sentence thank-you letter to your partner, out loud and quietly.",
    steps: ['One starts "Dear…" and says three sentences', "The other answers with one sentence", "Swap"],
    photoHint: "The two of you after the letters",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-029",
    category: "deep",
    title: "Good team",
    prompt: "What makes you two a good team? Each name one thing, with an example.",
    steps: ["One names a strength and an example", "The other adds a second example of it", "Swap"],
    photoHint: "A team photo",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-030",
    category: "deep",
    title: "Proud of us",
    prompt: "What are you proud of that you two did together? Big or small.",
    steps: ["One tells the story", 'The other asks, "What was the best part?"', "Swap"],
    photoHint: "Your proudest team pose",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  // Wrap-up
  {
    id: "wrapup-001",
    category: "wrapup",
    title: "Best bit",
    prompt: "What was the best moment of today's walk?",
    steps: ["Each name one moment", "The other says why they liked it too"],
    photoHint: "Recreate the best moment in one pose",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-002",
    category: "wrapup",
    title: "Headline",
    prompt: "Write today's newspaper headline about your walk. Make it big news.",
    steps: ["Each suggest a headline", "Pick one, or combine them"],
    photoHint: "The front-page photo for your headline",
    tags: ["talk", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-003",
    category: "wrapup",
    title: "One word",
    prompt: "Sum up this walk in one word each. Then explain your word in one sentence.",
    steps: ['Say your words at the same time on "three"', "Explain them"],
    photoHint: 'You two, each "saying" your word with your face',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-004",
    category: "wrapup",
    title: "Awards night",
    prompt: "It's awards night. Give your partner an award for today.",
    steps: ['Invent the award ("Best Opera Voice")', "Present it with a short speech", "Swap"],
    photoHint: "The winner holding an invisible trophy",
    tags: ["voice", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-005",
    category: "wrapup",
    title: "Next little thing",
    prompt: "Plan one small thing to do together this week. Free and easy.",
    steps: ["Each suggest one idea", "Pick one and a day"],
    photoHint: "You two shaking on the plan",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-006",
    category: "wrapup",
    title: "Keep this one",
    prompt: "Choose one detail from today you both want to remember in a year.",
    steps: ["Each suggest a detail", "Agree on one", "Say it out loud together"],
    photoHint: "Something that shows the detail",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-007",
    category: "wrapup",
    title: "Postcard home",
    prompt: "Say a two-line postcard to your future selves about today.",
    steps: ["Take one line each", 'Start with "Dear us,"', "End with a sign-off you both like"],
    photoHint: "The postcard front: you two and the view",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-008",
    category: "wrapup",
    title: "Rate it in ducks",
    prompt: "Rate today's walk out of five ducks. Or five clouds. Or five anything.",
    steps: ["Pick the unit together", "Each give a score and one reason"],
    photoHint: "Your scores, shown with your fingers",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-009",
    category: "wrapup",
    title: "Walking with you",
    prompt: "What did you like about walking with your partner today?",
    steps: ["One tells", "The other says thank you", "Swap"],
    photoHint: "A final selfie, closer than the first",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-010",
    category: "wrapup",
    title: "Victory pose",
    prompt: "You finished the quest. Celebrate like you just won something big.",
    steps: ["Count to three together", "Do your victory pose", "Do it once more, as a team"],
    photoHint: "The victory pose",
    tags: ["move", "energetic"],
    minutes: 2,
  },
  {
    id: "wrapup-011",
    category: "wrapup",
    title: "Not on the sofa",
    prompt: "Name one thing you did today that you would not have done on the sofa.",
    steps: ["Each name one thing", "The other says what they liked about it"],
    photoHint: "You two, very much not on a sofa",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-012",
    category: "wrapup",
    title: "That moment",
    prompt: "Name one moment on this walk when you found your partner attractive.",
    steps: ["One names the moment", "The other says thank you", "Swap"],
    photoHint: "That look again",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-013",
    category: "wrapup",
    title: "Small kindness",
    prompt: "Each choose one small, kind thing to do for the other before your next quest. Say it out loud.",
    steps: ["Each choose your kindness", "Say it out loud", "Shake on it"],
    photoHint: "The handshake",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-014",
    category: "wrapup",
    title: "Hands free",
    prompt: "One last photo: both of you in it, no phone in your hands.",
    steps: ["Find a safe place to lean the phone, or use the timer", "Get close", "Take the photo"],
    photoHint: "That photo",
    tags: ["quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-015",
    category: "wrapup",
    title: "Three fast thanks",
    prompt: "Say three tiny thank-yous for this walk, as fast as you can.",
    steps: ["One says three thank-yous fast", "The other does the same", "Pick your favourite"],
    photoHint: "You two, laughing",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-016",
    category: "wrapup",
    title: "Surprise",
    prompt: "What surprised you today, about this place or about your partner?",
    steps: ["One tells", "The other says what surprised them", "Compare"],
    photoHint: "Your surprised faces",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-017",
    category: "wrapup",
    title: "Next direction",
    prompt: "Where should your next walk go? Each suggest a direction or a place.",
    steps: ["Each suggest one", "Agree on one", "Point towards it"],
    photoHint: "You two, pointing the way",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-018",
    category: "wrapup",
    title: "Film critics",
    prompt: "Review today's walk like film critics: stars, best scene, best actor.",
    steps: [
      "One gives the stars and the best scene",
      "The other names the best actor and why",
      "Agree on a final score",
    ],
    photoHint: "Two critics, thumbs up",
    tags: ["voice", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-019",
    category: "wrapup",
    title: "Learned today",
    prompt: "Say one new thing you learned about your partner today.",
    steps: ["One says it", "The other says whether they knew it themselves", "Swap"],
    photoHint: "You two, looking a little wiser",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-020",
    category: "wrapup",
    title: "Hashtag",
    prompt: "Give today's walk a hashtag. Then each explain yours in one sentence.",
    steps: ["Each invent a hashtag", "Explain it", "Choose one for your album"],
    photoHint: "The photo for the hashtag",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-021",
    category: "wrapup",
    title: "Brag about us",
    prompt: "Brag about the two of you, as a team, to an imaginary friend.",
    steps: ["One starts the brag", "The other adds an even better detail", "End with a team pose"],
    photoHint: "The team pose",
    tags: ["voice", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-022",
    category: "wrapup",
    title: "Thank this place",
    prompt: "Thank this place out loud for the walk. Then thank each other.",
    steps: ["One thanks the place", "The other thanks the place too", "Then thank each other"],
    photoHint: "You two with this place behind you",
    tags: ["voice", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-023",
    category: "wrapup",
    title: "Code word",
    prompt: "Choose a word that will remind you of today. Use it as your secret code this week.",
    steps: ["Each suggest a word", "Pick one", "Say it together"],
    photoHint: 'You two "saying" the code word',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-024",
    category: "wrapup",
    title: "Walk interview",
    prompt: 'Interview each other: "How was your walk today?" Use your hand as a microphone.',
    steps: ["One interviews for 30 seconds", "The other answers like a star", "Swap"],
    photoHint: "The interview, microphone and all",
    tags: ["voice", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-025",
    category: "wrapup",
    title: "Top three",
    prompt: "Together, list today's top three moments, from third to first.",
    steps: ["Each suggest moments", "Agree on the top three", "Say number one together"],
    photoHint: "Number one, recreated",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-026",
    category: "wrapup",
    title: "Stop count",
    prompt: "High five once for every stop you reached. Then one big one for the team.",
    steps: ["Count the stops", "One high five each", "One big final high five"],
    photoHint: "The final high five",
    tags: ["move", "energetic"],
    minutes: 2,
  },
  {
    id: "wrapup-027",
    category: "wrapup",
    title: "Heart shape",
    prompt: "Make a heart shape together with your arms or hands.",
    steps: ["Decide: arms or hands", "Make the heart", "Hold it for the photo"],
    photoHint: "The heart",
    tags: ["move", "quiet"],
    minutes: 2,
  },
  {
    id: "wrapup-028",
    category: "wrapup",
    title: "Five words",
    prompt: "Describe today's walk in exactly five words, taking turns, one word each.",
    steps: ["One starts", "Take turns until you have five words", "Say the sentence together"],
    photoHint: "You two, showing five fingers",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-029",
    category: "wrapup",
    title: "Sound of today",
    prompt: "Make the sound of today's walk: a hum, a whistle, a laugh. Your partner adds theirs.",
    steps: ["One makes their sound", "The other adds theirs", "Make them together"],
    photoHint: "Your faces making the sound",
    tags: ["voice", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-030",
    category: "wrapup",
    title: "Glad you came",
    prompt: "Tell your partner one reason you are glad they came on this walk.",
    steps: ["One tells", "The other says thank you", "Swap"],
    photoHint: "A final selfie, close together",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
];
