import type { QuestTask } from "./types";

// Seed task pool: worked examples copied verbatim from docs/research/task-design-guide.md §5. The full pool will
// replace or extend this list; keep ids unchanged, since task history keys on them.
export const questTaskPool: QuestTask[] = [
  // Introductory
  {
    id: "intro-001",
    category: "intro",
    title: "Name this walk",
    prompt: "Every good adventure needs a title. Give today's walk the name of a film.",
    steps: ["Each suggest one title", "Pick one together, or mix them"],
    photoHint: "You two, looking like the film poster",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "intro-002",
    category: "intro",
    title: "Three words",
    prompt: "How do you feel right now? Say it in three words, then guess your partner's.",
    steps: ["Each think of three words", "Guess the other's first word", "Reveal and compare"],
    photoHint: "Your faces, showing word number one",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-003",
    category: "intro",
    title: "Small happy thing",
    prompt: "What small thing made you happy this week? Tell it like a tiny story.",
    steps: ["One tells", "The other asks one question about it", "Swap"],
    photoHint: "Two thumbs up, one each",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-004",
    category: "intro",
    title: "First thing I saw",
    prompt: "What is the first thing you noticed about your partner? Be honest and be kind.",
    steps: ["One tells", "The other says what they remember about that day", "Swap"],
    photoHint: "The same pose as your first photo together, if you remember it",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "intro-005",
    category: "intro",
    title: "Walk soundtrack",
    prompt: "If this walk had a song, what would it be? Hum a little of it.",
    steps: ["Each pick a song", "Hum ten seconds", "The other guesses it"],
    photoHint: 'A "music video" still of you two',
    tags: ["talk", "voice", "seated-ok"],
    minutes: 3,
  },

  // Silly game
  {
    id: "silly-001",
    category: "silly",
    title: "Nature film",
    prompt: "One of you is a rare animal. The other is a nature film narrator, whispering.",
    steps: [
      'Narrator whispers for 45 seconds about the "animal" and its habits',
      "Animal acts it out, quietly",
      "Swap",
    ],
    photoHint: "The rare animal in its natural home",
    tags: ["voice", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-002",
    category: "silly",
    title: "Human statue",
    prompt: 'Together, build one statue called "The Victory of Us".',
    steps: [
      "Agree on a pose in ten seconds",
      "Hold it, both still, for ten seconds",
      "Make a second version, bigger or smaller",
    ],
    photoHint: "The statue, of course",
    tags: ["move", "quiet"],
    minutes: 3,
  },
  {
    id: "silly-003",
    category: "silly",
    title: "Secret agents",
    prompt: "You are secret agents. Choose your code names and invent a secret handshake.",
    steps: ["Each pick the other's code name", "Build a handshake with at least four moves", "Do it twice, perfectly"],
    photoHint: "The handshake, mid-move",
    tags: ["move", "quiet", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-004",
    category: "silly",
    title: "Fake tour guide",
    prompt: "Pick the nearest ordinary thing: a bench, a tree, a lamp. Invent its amazing history.",
    steps: [
      "One is the proud guide for 30 seconds",
      "The other is a tourist and asks one question",
      "Swap, new object",
    ],
    photoHint: 'The guide presenting the "famous" object',
    tags: ["voice", "seated-ok"],
    minutes: 4,
  },
  {
    id: "silly-005",
    category: "silly",
    title: "One word each",
    prompt: 'Tell a story together, one word at a time. It starts with "Once, on a walk…"',
    steps: ["Take turns, one word each", "Keep going for one minute", "Give the story a title"],
    photoHint: "Your faces at the story's ending",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "silly-006",
    category: "silly",
    title: "Slow-motion race",
    prompt: "Find a safe, open spot. Race over ten steps, in slow motion. The slowest wins.",
    steps: ["Stand side by side", "Move as slowly as you can, with dramatic faces", "Replay the finish, even slower"],
    photoHint: "The dramatic finish",
    tags: ["move", "energetic", "outdoors-only"],
    minutes: 3,
  },

  // Deep task
  {
    id: "deep-001",
    category: "deep",
    title: "Thank you for",
    prompt: "Think of something small your partner did lately that you liked. Tell them, and say thank you.",
    steps: ["One tells the moment and says thank you", "The other says how it feels to hear it", "Swap"],
    photoHint: "Your hands together",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-002",
    category: "deep",
    title: "Good news, again",
    prompt: "Think of something that went well for you lately, big or small. Share it and celebrate it.",
    steps: [
      "One shares the good news",
      'The other asks, "How did it happen?" and one more question',
      'No "yes, but"',
      "Swap",
    ],
    photoHint: "A celebration pose for each win",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },
  {
    id: "deep-003",
    category: "deep",
    title: "Close to you",
    prompt: "When did you feel close to your partner lately? Pick one moment.",
    steps: ["One describes the moment: where, when, what happened", "The other says what they remember of it", "Swap"],
    photoHint: "You two, as close as feels right",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-004",
    category: "deep",
    title: "Hidden strength",
    prompt: "Tell your partner one strength they have that they might not see in themselves.",
    steps: ["One names the strength and gives an example", "The other repeats it back in their own words", "Swap"],
    photoHint: "Your partner, looking strong",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 5,
  },
  {
    id: "deep-005",
    category: "deep",
    title: "A little more of",
    prompt: "What is one small thing you would love a little more of from your partner?",
    steps: [
      'One says it, starting "I\'d love a little more…"',
      "The other repeats it back and says one way to try",
      "Swap",
    ],
    photoHint: 'Each of you, showing "a little" with your fingers',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 6,
  },

  // Wrap-up
  {
    id: "wrapup-001",
    category: "wrapup",
    title: "Best bit",
    prompt: "What was the best moment of today's walk?",
    steps: ["Each name one moment", "The other says why they liked it too"],
    photoHint: "Recreate the best moment in one pose",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-002",
    category: "wrapup",
    title: "Headline",
    prompt: "Write today's newspaper headline about your walk. Make it big news.",
    steps: ["Each suggest a headline", "Pick one, or combine them"],
    photoHint: "The front-page photo for your headline",
    tags: ["talk", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-003",
    category: "wrapup",
    title: "One word",
    prompt: "Sum up this walk in one word each. Then explain your word in one sentence.",
    steps: ['Say your words at the same time on "three"', "Explain them"],
    photoHint: 'You two, each "saying" your word with your face',
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 2,
  },
  {
    id: "wrapup-004",
    category: "wrapup",
    title: "Awards night",
    prompt: "It's awards night. Give your partner an award for today.",
    steps: ['Invent the award ("Best Opera Voice")', "Present it with a short speech", "Swap"],
    photoHint: "The winner holding an invisible trophy",
    tags: ["voice", "seated-ok"],
    minutes: 3,
  },
  {
    id: "wrapup-005",
    category: "wrapup",
    title: "Next little thing",
    prompt: "Plan one small thing to do together this week. Free and easy.",
    steps: ["Each suggest one idea", "Pick one and a day"],
    photoHint: "You two shaking on the plan",
    tags: ["talk", "quiet", "seated-ok"],
    minutes: 3,
  },
];
